### ISSUE TITLE
Use CameraPublisher for publishing images and intrinsics

### ISSUE THREAD

**Issue by christianrauch** [klintan/ros2_usb_camera#1]
It would be useful to use the [`image_transport::CameraPublisher`](https://github.com/ros-perception/image_common/blob/eb4680dcfa35fc47e5f0329916a37d743323fd6c/image_transport/include/image_transport/camera_publisher.h#L67) to publish images and the intrinsic parameters. It would also allow to switch between raw and compressed images via user configuration.

**Comment by klintan** [comment]
I'm actually already using it, 
```
    camera_info_pub_ = image_transport::create_camera_publisher(this, "image_raw", custom_qos_profile);
```
Are you on the `dashing-devel` branch? I'll update the master branch to be the latest.

**Comment by klintan** [comment]
I'll close this one. If you still face this issue/don't see the camerapublisher, feel free to open a new issue.
