### ISSUE TITLE
Camera topic can not be visualized in Rviz2

### ISSUE THREAD

**Issue by minutiaes** [klintan/ros2_usb_camera#10]
Hello, I am using your package with ros eloquent. It is working and I can see the topic content in terminal but Rviz2 can not display the image topic. I get a warning something like:

_[INFO] [rviz]: Message Filter dropping message: frame 'camera' at time 1606668158.242 for reason 'Unknown'_

**Comment by klintan** [comment]
Hey! 

Hm I had a similar issues with displaying in RVIZ2 but at that time I thought it was something with RVIZ2. I'm pretty sure I tried with some other package (I have a video-streamer as well) maybe try that and see if it works? If possible I would also try Foxy and rviz2 with the package to see if it works (if there is some issue with RVIZ2 in Eloquent)

If not I'll have to dig in to try to figure it out. Let me know what happens,

**Comment by minutiaes** [comment]
Later I had written a package in python quickly and the result was the same. After that I have noticed that the problem is the fixed frame in Rviz2. As default "map" is the fixed frame and when it is changed to "camera", everything works fine.

p.s. in my case there is not any tf topic yet which describes coordinate frame relationships so that's why I modify fixed frame.

**Comment by klintan** [comment]
Great catch. Thanks for letting me and others know, I probably had the same issue then!
