### ISSUE TITLE
Create foxy-devel branch

### ISSUE THREAD

**Issue by agutenkunst** [klintan/ros2_usb_camera#11]
Hi @klintan 
First: Thanks for this package! I am using you package with ros2 foxy to get images from a webcam and it is working quite well so far ;-)

Would you mind opening a foxy-devel branch? Would you be up for an release of this package?

Greetings!

**Comment by klintan** [comment]
Hey, 
Thanks! I'm glad to hear that :)  Yes def, I created a foxy-devel branch so feel free to create a PR. 

That would be awesome, I haven't done any ROS2 releases though, do you have any experience with that ?

**Comment by agutenkunst** [comment]
Thank you!

Considering the release I only have experience in releasing ROS1 packages.
But according to https://index.ros.org/doc/ros2/Tutorials/Releasing-a-ROS-2-package-with-bloom/#no-differences-from-ros-1-bloom it works just the same way. However I am not sure if the package must/should/could run on all OS (including Win/MacOS). 

I'll open a draft PR son since I am not entirly sure about the component / non-component launch file.

**Comment by agutenkunst** [comment]
@klintan PR now ready. But at draft stage for now.
