### ISSUE TITLE
Package and node name

### ISSUE THREAD

**Issue by ipa-kut** [klintan/ros2_usb_camera#2]
Thank you for developing this driver! I tested the base publisher (uncompressed) on eloquent and it worked. I noticed that the frame rate felt a bit choppy, however.

I used the branch `dashing-devel`, but it seems in both of the branches the name of the package and executable is slightly different to your readme.

**Comment by klintan** [comment]
Thanks for your contribution, I'll create an eloquent-branch shortly, but as you said I think it should work out of the box. Some differences how you pass the params though etc.
